baseURL: 'https://hexann666.github.io/recipe2pdf.github.io/'
languageCode: 'en-us'
title: 'Recipe to PDF'
theme: 'ghostwriter'


pygmentsUseClasses: true
pygmentsCodefences: true

params:
  mainSections:
    - posts
  intro: true
  headline: Recipe to PDF documentation
  github: "https://github.com/recipe2pdf.github.io"
  gitlab: "https://gitlab.web.fh-kufstein.ac.at/anna.fedorova/recipe2pdf"
  linkedin: "https://www.linkedin.com/in/anna-fedorova-ba9a30177/"
  email: 2110837178@stud.fh-kufstein.ac.at
  shareLinkedIn: True
  #description: Ghostwriter example description

menu:
  main:
    - name: About
      url: /page/about
      weight: 1
    - name: Blog
      url: /
      weight: 2
    - name: Requirements
      url: /page/requirements/
      weight: 3
    